[[resources]]

== Resources

=== Introduction

As described in the abstract model, a GSS service has four distinct functional
capabilities. 

* It manages events and event channels for disseminating those events.
* It manages publications which are ad-hoc event channels derived from the three basic event channels that a GSS manages (see <<EventChannels,Event Channels>>)
* It implements a change management API that allows proposed changes to be reviewed, either manually or automatically, and either be accepted or rejected.
* It implements a query API that allows event channels to be queried based on spatial and non-spatial predicates where spatial predicates can include both geometric and temporal predicates.
* It may implement a subscription interface to allow interested parties to be notified of events and also allows the GSS to act as a synchronization agent keeping one or more target feature type synchronized with a source feature type within the control domain of the GSS.

This clause describes an implementation of a GSS where:

* Events are implemented as ATOM entries.
* Event channels and publications are implemented as ATOM feeds.
* Feed management may be performed using the ATOM Publishing Protocol (see IETF RFC 5023) although other bindings are described as well.
* A query operation is defined that supports both spatial and non-spatial predicates.  The operation is compatible with OpenSearch and the OpenSearch geo and time extensions.
* A subscription API is defined to create and manage subscriptions and to enable synchronization.

[[BaseFeeds]]
=== Event channels

==== Introduction

Feeds are maintained by the Geo-Synchronization service on behalf of participants
collaborating in an environment composed of distributed WFS servers.  In
addition to feeds, a GSS also maintains publications which are filtered feeds.
There are three main ATOM feeds used to implement Geo-Synchronization.

* A Proposed Change feed
* A Resolution feed
* A Replication feed.

Interested parties can subscribe to any of these feeds, or publications derived
from those feeds, to be notified whenever entries are created or modified.

[[EncodingRules,Encoding Rules for Feed Entries]]
==== Encoding

include::requirements/REQ083.adoc[]

==== Proposed change feed

include::requirements/REQ071.adoc[]

Any authorized user can post entries to the Proposed Change Feed.  

include::requirements/REQ072.adoc[]

include::requirements/REQ073.adoc[]

If an ATOM element does not appear in this table then it may be omitted or populated as described in the ATOM specification (see IETF RFC 4287).

Additional elements may appear in the change feed entry but they are not 
described in this standard.

[#ChangeFeedElements,reftext='{Change feed elements} {counter:table-num}']
.Change feed elements
[width="90%",cols="20%,20%,60%"]
|===
|ATOM Entry Element |M/O |Description 
|content |M |The content element shall contain a description of the proposed change.  All servers that comply to this standard shall be able to process a change proposal encoded using a wfs:Transaction element.  
|id |M |The Id element shall be present.  The content of the Id element may be empty.  If the content is empty then the server shall generate an id (in the form of a uuid) for the entry.  If the content is not empty then it shall be an identifier for the entry generated by the client in the form of a uuid.  The server shall preserve client generated uuid's. (Example: urn:uuid:26b3c614- b761-4f7c-a011-c2c15642cc3a.)
|link |M |There shall be a single link element with the value of the "rel" attribute set to "targetServer" and the value of the "href" attribute  set to the GetCapabilities URL of the WFS to which this change is to be applied.
|link |O |There shall be one or more link elements with the value of the "rel" attribute set to "targetFeature" and the value of the "href" attribute set to point to a feature that is being changed or deleted by the proposed change transaction.
|summary |O |May contain a short description about the change. Similar to a log entry someone might put into a Subversion, Concurrent Versions System, Git or other version management system. Example: "Telephone pole moved 10m North as per observed position from onsite crew."
|title |M |Shall contain a title describing what is being changed.  For example: "Proposed change for feature INWATERA_1M.1013.".
|updated |M |The date the change was made. All times shall be Greenwich Mean Time (GMT).
|georss:where |O |If the feature being changed is non-spatial then the element shall not be specified. If the feature is spatial and includes a single point geometry then that geometry shall be used as the value of element. Otherwise a gml:Envelope containing the geometry shall be used as the value of the georss:where element.
|===

Note: The GSS is actually agnostic of how proposed changes are encoded.  For this version of the standard we specify the use of wfs:Transactions because the only OGC web service currently being geosynchronized is the web feature service.  In the future, however, other OGC (and perhaps non-OGC) services may be geosynchronized and the payload of the content element will correspond to how transactions are encoded for those target services.

Note: In the original CGDI pilot project that initiated the development of this standard, it was envisioned that a change proposal could be encoded as narrative text for even a GML fragment expressing the proposed new state of a feature.  In practice, however, changes have been encoded as wfs:Transaction elements since the target servers were always OGC WFS's.

Example: 
<atom:link 
rel="targetServer"
href=http://demo.cubewerx.com/cubeserv/cubeserv.cgi?config=DEMO&datastore=DEMO&service=WFS&request=GetCapabilities/> 
This allows the change feed to be filtered for entries that apply to a particular server.

Example:
<atom:link rel="targetFeature" href=http://demo.cubewerx.com/cubeserv/cubeserv.cgi?config=DEMO&datastore=DEMO&service=WFS&version=1.1.0&request=GetFeature&typeName=Roads&featureId=10/>

==== Resolution feed

include::requirements/REQ025.adoc[]

When a proposed change is accepted or rejected, the Resolution Feed is updated
to indicate the disposition of the change.  Users can subscribe to the
Resolution feed to be notified when a decision is reached about their proposed
change(s).

include::requirements/REQ026.adoc[]

If an ATOM element does not appear in this table then is may be omitted or
populated as described in the ATOM specification (see IETF RFC 4287).

Additional elements may appear in the resolution feed entry but they are not 
described in this standard.

[#ResolutionFeedElements,reftext='{Resolution feed elements} {counter:table-num}']
.Resolution feed elements
[width="90%",cols="20%,20%,60%"]
|===
|ATOM Entry Element |M/O |Description
|Author |M |Shall be populated with the contact information for the data custodian that may be contacted to ask questions about the resolution.
|Category |M |There shall be at one category element in the entry indicating the disposition of the originating change proposal. The "term" attribute shall have a value of "Accepted" if the originating change proposal was accepted or "Rejected" if the originating change proposal was rejected. The scheme attribute shall have the value: "http://www.opengis.org/geosync/resolutions"
|Content |M |If the change proposal was rejected then the content element may contain a narrative describing why it was rejected.  If the change proposal was accepted but modified then the content element may contain a narrative describing the modifications.
|Id |M |An id for the resolution feed entry.
|link |M |A link with the value of the "rel" attribute set to "disposition" and the value of the href attribute set to point to the change feed entry that has been accepted or rejected.
|title |M |The value of the title element shall be 'Proposal Accepted' or 'Proposal Rejected' depending of the disposition of the originating change proposal.
|updated |M |The date the change was made. All time shall be Greenwich Mean Time (GMT).
|georss:where |O |If the originating change proposal was rejected, the georss:where element shall be omitted.  If the originating change proposal was accepted, the georss:where element shall have a value according to the following rules: If the modified feature is non-spatial then the element shall not be specified. If the modified feature is spatial and includes a single point geometry then that geometry shall be used as the value of element. If the modified feature is spatial and includes a non-single point geometry then a gml:Envelope containing the geometry shall be used as the value of the <georss:where>element.
|===

==== Replication feed

The Replication Feed is a log of changes that have been applied to features 
offered by web feature servers within the control domain of a GSS.

Interested parties can then use the entries in the Replication feed to
synchronize a local copy of the data with the data provider's data store.
Synchronization can be performed by an agent external for the GSS or interested
parties can subscribe to the Replication Feed or a derived publication and have
the GSS perform the synchronization.

include::requirements/REQ075.adoc[]

If an ATOM element does not appear in this table then is may be omitted or
populated as described in the ATOM specification (see IETF RFC 4287). Additional
elements may appear in the change feed entry but they are not described in this
standard.

[#ReplicationFeedElements,reftext='{Replication feed elements} {counter:table-num}']
.Replication feed elements
[width="90%",cols="20%,20%,60%"]
|===
|ATOM Entry Element |M/O |Description
|author |M |Shall be populated with a responsible party at the source server that can be contacted in case of problems.
|category |M |There shall be one category element in the entry indicating the type of change that was applied to a geographic feature. The "term" attribute shall have a value of "insert", "update" or "delete". The scheme attribute shall have the value: "http://www.opengis.org/geosync/actions"
|category |M |There shall be one category element in the entry indicating the feature type that the applied change affected.  The value of "term" attribute shall be the qualified name of the feature type.  The scheme attribute shall have the value "http://www.opengis.org/geosync/featureType"
|content |M |The content element shall contain a wfs:Transaction element that in-turn contain the action (Insert, Update or Delete) that has been applied to the feature.  The value of the type attribute on the content element shall be "application/gml+xml; version=N.N" where N.N indicates the version of GML being used to encode the feature and may include additional components for profiles.
|id |M |The id element shall be present.  The content of the id element may be empty.  If the content is empty then the server shall generate an id (in the form of a uuid) for the entry.  If the content is not empty then it shall be an identifier for the entry generated by the client in the form of a uuid.  The server shall preserve client generated uuid's.
|link |M |There shall be one link element in the entry, with the value of the "rel" attribute set to "server" that contains the base URL of the server that serves the changed or created feature.
|link |O |There may be one link element in the entry, with the value of the "rel" attribute set to "feature", that fetches the feature from the source server. This element shall only be populated if the server supports versioning and can fetch the version of the feature that contains the change described by the entry. Otherwise the link shall not be populated.
|summary |O |May contain a short description about the change. Similar to a log entry someone might put into an svn or cvs log. (Example: "Telephone pole moved 10m North as per observed position from onsite crew.")
|title |M |Shall be populated with the value: "<OP> of feature <FID>" where "<OP>" is one of Insert, Update or Delete and <FID> is the feature id of the feature being affected.
|updated |M |The date the change was made. All time shall be Greenwich Mean time (GMT).
|georss:where |O |If the feature is non-spatial then the element shall not be specified. If the feature is spatial and includes a single point geometry then that geometry shall be used as the value of element. Otherwise a gml:Envelope containing the geometry shall be used as the value of the <georss:where>element.
|===

As described in OGC 09-025r2, OpenGIS Web Feature Service (WFS) Implementation
Specification, a single wfs:Transaction element may contain multiple insert,
update and/or delete actions affecting multiple features (see http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#269).

include::requirements/REQ076.adoc[]

If the entries in the replication feed are based on "commits", rather than
individual features it becomes difficult to isolate particular features of
interest.  Including a wfs:Transaction element describing the change in the
replication feed allows subscribers to follow features either individually
or sets thereof using an OGC filter expression.  

The OGC filter expression can identify individual features to sets of features
using temporal, spatial and non-spatial predicates.  So, for example, it is
conceivable to follow a single features like the boundary of an oil slick or to
follow sets of  features that lies within a the boundary of a state or province.

[[PublicationEncoding,Publication encoding]]
=== Publication encoding

The following XML Schema fragment defines the XML encoding for a publication:

[source,xml]
   <xsd:element name="Publication"
                substitutionGroup="pubsub:Publication">
      <xsd:complexType>
         <xsd:complexContent>
            <xsd:extension base="pubsub:DerivedPublicationType">
               <xsd:sequence>
                  <element name="AdditionalPublicationIdentifier"
                           type="pubsub:PublicationIdentifierType"
                           minOccurs="0" maxOccurs="0"/>
               </xsd:sequence>
               <xsd:attribute name="owner" type="xsd:string"/>
            </xsd:extension>
         </xsd:complexContent>
      </xsd:complexType>
   </xsd:element>

include::requirements/REQ084.adoc[]

Content may be aggregated in a publication by, in addition to the
pubsub:BasePublicationIdentifier, specifying one or more
gss:AdditionalPublicationIdentifier elements.

It is recommended that a publication include a ows:Title element.

include::requirements/REQ085.adoc[]

include::requirements/REQ086.adoc[]

A publication may include a filter that identifies the subset of entries from
the base publication(s) that appear in a publication. For example, a spatial
predicate may be specified to restrict publication entries to those that lie
within an area of interest.

include::requirements/REQ087.adoc[]

Other predicate languages are allowed but are not described in this standard.

include::requirements/REQ091.adoc[]

[[SubscriptionEncoding,Subscription encoding]]
=== Subscription encoding

A subscription signals to a GSS that a subscriber wishes to be notified
whenever new entries satisfy the predicates specified when the publication
was created.

The following XML Schema fragment defines the XML encoding for a subscription:

[source,xml]
   <xsd:element name="Subscription"
                substitutionGroup="pubsub:Subscription">
      <xsd:complexType>
         <xsd:complexContent>
            <xsd:extension base="pubsub:SubscriptionType">
               <xsd:attribute name="owner" type="xsd:string"/>
            </xsd:extension>
         </xsd:complexContent>
      </xsd:complexType>
   </xsd:element>

include::requirements/REQ088.adoc[]

include::requirements/REQ089.adoc[]

=== Resource URIs

==== Introduction

For servers that implement the REST binding, this clause defines the resource
URIs for the base feeds, base feed entries, review resource, publications,
publication entries and subscriptions.

[[BaseFeedURIs,Base feed URIs]]
==== Base feed URIs

As described in <<EventChannels,Event Channels>>, a GSS offers three base feeds: the change feed,
the resolution feed and the replication feed.

include::requirements/REQ078.adoc[]

For servers that implement the REST binding, the following table lists the
URIs for each of the GSS base feeds.

[width="90%",cols="20%,80%"]
|===
|Resource URI |Description
|/changefeed |Each entry in the change feed represent a proposed change to feature within the control domain of a GSS.
|/resolutionfeed |Each entry in the resolution feed describes the disposition of each proposed change (i.e. accept or reject)
|/replicationfeed |Each entry in the replication feed described a change applied to a feature that is within the control domain of a GSS
|===

[[BaseFeedEntryURIs,Base feed entry URIs]]
==== Base feed entry URIs

include::requirements/REQ079.adoc[]

Example: .../changefeed/urn:uuid:e7b2da53-2092-48a8-ac31-dd461e99ad8f

==== Review URIs

include::requirements/REQ042.adoc[]

The "/accepted" and "/rejected" resource is used to accept or reject proposed
changes.

[[PublicationURIs,Publication URIs]]
==== Publication URIs

include::requirements/REQ029.adoc[]

Publication URIs are opaque and generated by the GSS when a publication is
created.

include::requirements/REQ080.adoc[]

==== Publication entry URIs

include::requirements/REQ081.adoc[]

Example: .../features_in_quebec/urn:uuid:e7b2da53-2092-48a8-ac31-dd461e99ad8f

[[SubscriptionURIs,Subscription URIs]]
==== Subscription URIs

include::requirements/REQ030.adoc[]
